# Generated by Django 5.1.15 on 2026-07-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена')], default='new', max_length=12, verbose_name='Статус')),
                ('org', models.CharField(max_length=200, verbose_name='Организация')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('resident', models.BooleanField(default=False, verbose_name='Резидент ИНТЦ')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Стоимость, ₽')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка, ₽')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Итого, ₽')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('type', models.CharField(choices=[('room', 'Лаборатория'), ('equipment', 'Оборудование'), ('specialist', 'Специалист'), ('service', 'Услуга под ключ')], max_length=12, verbose_name='Тип')),
                ('category', models.CharField(blank=True, choices=[('bio', 'Биотехнологии'), ('pharma', 'Фармацевтика'), ('micro', 'Микроэлектроника'), ('vacuum', 'Вакуум и испытания'), ('genetics', 'Молекулярная генетика'), ('materials', 'Новые материалы'), ('food', 'Функциональное питание'), ('analytics', 'Аналитика')], max_length=12, verbose_name='Направление')),
                ('book_mode', models.CharField(choices=[('shift', 'Смена (8 ч)'), ('day', 'Сутки'), ('hour', 'Час'), ('sample', 'Образец')], max_length=8, verbose_name='Единица брони')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('lab', models.CharField(blank=True, max_length=160, verbose_name='Подразделение / лаборатория')),
                ('clean_class', models.CharField(blank=True, max_length=60, verbose_name='Класс чистоты / статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('specs', models.JSONField(blank=True, default=list, verbose_name='Характеристики (список)')),
                ('price_value', models.PositiveIntegerField(default=0, verbose_name='Цена, ₽')),
                ('price_unit', models.CharField(default='час', max_length=20, verbose_name='Единица цены')),
                ('min_units', models.PositiveSmallIntegerField(default=1, verbose_name='Мин. единиц')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Ключ/URL фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('bundled_with', models.ManyToManyField(blank=True, to='booking.resource', verbose_name='Входит в комплект')),
                ('requires_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operates', to='booking.resource', verbose_name='Требует оператора')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Каталог ресурсов',
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BusySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('slot_start', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('slot_end', models.TimeField(blank=True, null=True, verbose_name='Окончание')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Пометка')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy', to='booking.resource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Занятость',
                'verbose_name_plural': 'Календарь занятости',
                'ordering': ['date', 'slot_start'],
            },
        ),
        migrations.CreateModel(
            name='BookingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('slot_start', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('slot_end', models.TimeField(blank=True, null=True, verbose_name='Окончание')),
                ('qty', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во')),
                ('hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Часы')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='Цена/ед.')),
                ('line_price', models.PositiveIntegerField(default=0, verbose_name='Сумма строки')),
                ('is_operator', models.BooleanField(default=False, verbose_name='Оператор к прибору')),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='booking.bookingline')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='booking.order', verbose_name='Заявка')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.resource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
            },
        ),
    ]
