# Generated by Django 5.1.15 on 2026-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='units_total',
            field=models.PositiveSmallIntegerField(default=1, help_text='Сколько одинаковых единиц ресурса есть физически (приборов, мест, специалистов).', verbose_name='Единиц в наличии'),
        ),
    ]
