# Generated by Django 5.1.15 on 2026-07-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_resource_units_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Телефон'),
        ),
    ]
