# Generated by Django 5.1.15 on 2026-07-08 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_order_contact_name_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='work_end',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Работает до'),
        ),
        migrations.AddField(
            model_name='resource',
            name='work_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Работает с'),
        ),
    ]
