# Generated by Django 5.1.15 on 2026-07-09 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_resource_work_end_resource_work_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Организация')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('category', models.CharField(blank=True, choices=[('bio', 'Биотехнологии'), ('pharma', 'Фармацевтика'), ('micro', 'Микроэлектроника'), ('vacuum', 'Вакуум и испытания'), ('genetics', 'Молекулярная генетика'), ('materials', 'Новые материалы'), ('food', 'Функциональное питание'), ('analytics', 'Аналитика')], max_length=12, verbose_name='Направление')),
                ('resident', models.BooleanField(default=True, verbose_name='Резидент ИНТЦ')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирована')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='booking.company', verbose_name='Компания'),
        ),
    ]
