# Generated by Django 5.1.15 on 2026-07-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_company_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждена оператором'),
        ),
        migrations.AlterField(
            model_name='company',
            name='resident',
            field=models.BooleanField(default=False, verbose_name='Резидент ИНТЦ'),
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('key', models.CharField(choices=[('rid', 'Количество РИД'), ('rnd', 'Инвестиции в НИОКР'), ('infra', 'Инвестиции в инфраструктуру'), ('staff', 'Численность работников'), ('revenue', 'Выручка'), ('export', 'Доля экспорта')], max_length=12, verbose_name='Показатель')),
                ('plan', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='План')),
                ('fact', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Факт')),
                ('document', models.FileField(blank=True, null=True, upload_to='kpi_docs/', verbose_name='Подтверждающий документ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='booking.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'ordering': ['company', '-year'],
                'unique_together': {('company', 'year', 'key')},
            },
        ),
    ]
