# Generated by Django 5.1.15 on 2026-07-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_company_confirmed_alter_company_resident_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Сумма / количество')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('document', models.FileField(blank=True, null=True, upload_to='kpi_docs/', verbose_name='Документ')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Из документа')], default='manual', max_length=8, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='booking.kpi', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Позиция показателя',
                'verbose_name_plural': 'Позиции показателей',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
