# Generated by Django 5.1.15 on 2026-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_kpientry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_request',
            field=models.TextField(blank=True, verbose_name='Запрос на изменение (от компании)'),
        ),
    ]
