# Generated by Django 5.1.15 on 2026-07-31 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_order_change_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="Номер"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_work", "В работе"),
                            ("done", "Обработана"),
                            ("rejected", "Отклонена"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "org",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Организация"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Контактное лицо"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Телефон"),
                ),
                ("need", models.TextField(verbose_name="Что требуется")),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text="Заполняется по желанию клиента.",
                        max_length=200,
                        verbose_name="Желаемые сроки",
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Что искали"
                    ),
                ),
                (
                    "operator_note",
                    models.TextField(blank=True, verbose_name="Комментарий оператора"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_requests",
                        to="booking.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальная заявка",
                "verbose_name_plural": "Индивидуальные заявки",
                "ordering": ["-created_at"],
            },
        ),
    ]
