# Generated by Django 5.1.15 on 2026-07-31 17:59

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_customrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="kpi_docs/",
                validators=[booking.models.validate_doc_file],
                verbose_name="Подтверждающий документ",
            ),
        ),
        migrations.AlterField(
            model_name="kpientry",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="kpi_docs/",
                validators=[booking.models.validate_doc_file],
                verbose_name="Документ",
            ),
        ),
    ]
