# Generated by Django 5.1.15 on 2026-08-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_kpi_document_alter_kpientry_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Название проекта"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="Суть в двух фразах"),
                ),
                (
                    "problem",
                    models.TextField(blank=True, verbose_name="Какую задачу решаете"),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True, verbose_name="Как решаете и в чём новизна"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("idea", "Идея"),
                            ("calc", "Расчёты и моделирование"),
                            ("lab", "Лабораторный образец"),
                            ("proto", "Опытный образец"),
                            ("test", "Испытания"),
                            ("serial", "Серийное производство"),
                        ],
                        max_length=12,
                        verbose_name="Стадия готовности",
                    ),
                ),
                (
                    "groundwork",
                    models.TextField(blank=True, verbose_name="Научный задел"),
                ),
                ("team", models.TextField(blank=True, verbose_name="Команда")),
                (
                    "market",
                    models.TextField(blank=True, verbose_name="Рынок и его объём"),
                ),
                (
                    "competitors",
                    models.TextField(blank=True, verbose_name="Конкуренты и отличия"),
                ),
                (
                    "business_model",
                    models.TextField(
                        blank=True, verbose_name="Как проект зарабатывает"
                    ),
                ),
                (
                    "workplan",
                    models.TextField(blank=True, verbose_name="План работ по этапам"),
                ),
                ("risks", models.TextField(blank=True, verbose_name="Риски")),
                (
                    "needs",
                    models.TextField(
                        blank=True, verbose_name="Какое оборудование и методы нужны"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="booking.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль проекта",
                "verbose_name_plural": "Профили проектов",
            },
        ),
    ]
