# Generated by Django 5.1.15 on 2026-08-01 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_projectprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fmt", models.CharField(max_length=32, verbose_name="Формат")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Выполняется"),
                            ("done", "Готово"),
                            ("failed", "Не удалось"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "mode",
                    models.CharField(blank=True, max_length=10, verbose_name="Режим"),
                ),
                (
                    "blocks",
                    models.JSONField(blank=True, default=list, verbose_name="Блоки"),
                ),
                (
                    "gaps",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Чего не хватило"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compose_jobs",
                        to="booking.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сборка документа",
                "verbose_name_plural": "Сборки документов",
                "ordering": ["-created_at"],
            },
        ),
    ]
