# Generated by Django 5.1.15 on 2026-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="consent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Согласие на обработку ПДн"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="consent_version",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Редакция политики"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="founded",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="ogrn",
            field=models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
        ),
        migrations.AddField(
            model_name="company",
            name="okved",
            field=models.CharField(
                blank=True,
                help_text="Основной и дополнительные, через запятую.",
                max_length=200,
                verbose_name="ОКВЭД",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="revenue",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Выручка за прошлый год, ₽"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="staff",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Численность"
            ),
        ),
    ]
