# Generated by Django 5.1.15 on 2026-08-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_company_consent_at_company_consent_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Программа")),
                (
                    "fund",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Кто проводит"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Страница программы")),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать резидентам"
                    ),
                ),
                (
                    "opens_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Приём заявок с"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Приём заявок до"
                    ),
                ),
                (
                    "max_grant",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Предельный размер гранта, ₽",
                    ),
                ),
                (
                    "cofinancing_pct",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Доля от суммы гранта, которую заявитель вкладывает сам.",
                        null=True,
                        verbose_name="Требуемое софинансирование, %",
                    ),
                ),
                (
                    "min_age_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Компания не моложе, мес."
                    ),
                ),
                (
                    "max_age_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Компания не старше, мес."
                    ),
                ),
                (
                    "max_staff",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Численность не более"
                    ),
                ),
                (
                    "max_revenue",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Выручка не более, ₽"
                    ),
                ),
                (
                    "okved",
                    models.CharField(
                        blank=True,
                        help_text="Коды или их начала через запятую, напр. «72, 21.20». Пусто — программа не ограничивает.",
                        max_length=300,
                        verbose_name="Допустимые ОКВЭД",
                    ),
                ),
                (
                    "stages",
                    models.CharField(
                        blank=True,
                        help_text="Ключи стадий через запятую: idea, calc, lab, proto, test, serial. Пусто — любые.",
                        max_length=200,
                        verbose_name="Допустимые стадии проекта",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Показывается в кабинете как есть.",
                        verbose_name="Примечания для резидента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа поддержки",
                "verbose_name_plural": "Программы поддержки",
                "ordering": ["deadline", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Наименование"),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Цена за единицу, ₽"
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(blank=True, max_length=20, verbose_name="Единица"),
                ),
                (
                    "qty",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Одной строкой — попадёт в заявку как обоснование.",
                        max_length=300,
                        verbose_name="Зачем в проекте",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлена"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="booking.projectprofile",
                        verbose_name="Профиль проекта",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_lines",
                        to="booking.resource",
                        verbose_name="Позиция каталога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка сметы",
                "verbose_name_plural": "Смета проекта",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
