# Generated by Django 5.1.15 on 2026-08-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_program_budgetline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="revenue",
        ),
        migrations.RemoveField(
            model_name="company",
            name="staff",
        ),
    ]
