# Generated by Django 5.1.15 on 2026-08-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_remove_company_revenue_remove_company_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectprofile",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты резидентов",
            },
        ),
        migrations.AddField(
            model_name="composejob",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compose_jobs",
                to="booking.projectprofile",
                verbose_name="Проект",
            ),
        ),
        migrations.AlterField(
            model_name="projectprofile",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="booking.company",
                verbose_name="Компания",
            ),
        ),
    ]
