# Generated by Django 5.1.15 on 2026-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_alter_projectprofile_options_composejob_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bio", "Биотехнологии"),
                    ("pharma", "Фармацевтика"),
                    ("micro", "Микроэлектроника"),
                    ("vacuum", "Вакуум и испытания"),
                    ("genetics", "Молекулярная генетика"),
                    ("materials", "Новые материалы"),
                    ("food", "Функциональное питание"),
                    ("analytics", "Аналитика"),
                    ("other", "Другое"),
                ],
                max_length=12,
                verbose_name="Направление",
            ),
        ),
    ]
